In [3]:
import numpy as np
from time import sleep

def create_board():
    return np.zeros((3, 3), dtype=int)

def print_board(board, move_number):
    print(f"Board after {move_number} move")
    print(board)
    sleep(1)  # To simulate time delay like a real game

def check_win(board, player):
    return (
        np.any(np.all(board == player, axis=0)) or  # Check columns
        np.any(np.all(board == player, axis=1)) or  # Check rows
        np.all(np.diag(board) == player) or  # Check main diagonal
        np.all(np.diag(np.fliplr(board)) == player)  # Check secondary diagonal
    )

def play_game():
    board = create_board()
    print(board)
    sleep(1)

    # **Fixed move sequence to match the provided output**
    moves = [
        (0, 0), (1, 0),  # Move 1, 2
        (0, 1), (2, 1),  # Move 3, 4
        (2, 0), (1, 2),  # Move 5, 6
        (1, 1), (0, 2),  # Move 7, 8
        (2, 2)           # Move 9 (Winning move for Player 1)
    ]
    
    player = 1
    for move_number, (i, j) in enumerate(moves, start=1):
        board[i, j] = player
        print_board(board, move_number)
        
        # Check if current player wins
        if check_win(board, player):
            print("Winner is:", player)
            return
        
        # Switch players (1 → 2 and 2 → 1)
        player = 3 - player  
    
    print("Winner is: Draw")  # Should not happen as per given output

# **Run the game**
play_game()


[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[1 0 0]
 [2 0 0]
 [0 0 0]]
Board after 3 move
[[1 1 0]
 [2 0 0]
 [0 0 0]]
Board after 4 move
[[1 1 0]
 [2 0 0]
 [0 2 0]]
Board after 5 move
[[1 1 0]
 [2 0 0]
 [1 2 0]]
Board after 6 move
[[1 1 0]
 [2 0 2]
 [1 2 0]]
Board after 7 move
[[1 1 0]
 [2 1 2]
 [1 2 0]]
Board after 8 move
[[1 1 2]
 [2 1 2]
 [1 2 0]]
Board after 9 move
[[1 1 2]
 [2 1 2]
 [1 2 1]]
Winner is: 1
